name: Push docs

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'docs/'
        destination_repo: 'VarLad/QuantumBFS.github.io'
        user_email: '1805204@kiit.ac.in'
        user_name: 'varlad'
        commit_message: 'Pushing the docs to the site repo (master branch) from Yao.jl repo (master branch)'
        destination_branch: 'master'
